name: Scheduled jobs
on:
  schedule:
    - cron: '0 4 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: deweysasser/tools
      TAG: latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: docker build -t ${{env.TARGET}}:${{env.TAG}} .
        name: build
        env:
          DOCKER_BUILDKIT: 1
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - run: docker push ${{env.TARGET}}:${{env.TAG}}
        name: push
