name: Scheduled jobs
on:
  schedule:
    - cron: '0 4 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: deweysasser/tools
      TAG: latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Log in to github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        with:
          ref: main

      - run: docker build -t ${{env.TARGET}}:${{env.TAG}} .
        name: build
        env:
          DOCKER_BUILDKIT: 1

      - run: docker push ${{env.TARGET}}:${{env.TAG}}
        name: push to hub.docker.com

      - run: docker tag ${{env.TARGET}}:${{env.TAG}}  ghcr.io/${{env.TARGET}}:${{env.TAG}}
        name: retagging

      - run: docker push ghcr.io/${{env.TARGET}}:${{env.TAG}}
        name: push to ghcr.io